"""Колонка gif_count удалена из таблицы users из-за сложностей синхронизации

Revision ID: 4a18bf358b54
Revises: f67e8375822f
Create Date: 2025-08-19 13:54:44.253750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a18bf358b54'
down_revision: Union[str, Sequence[str], None] = 'f67e8375822f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gif_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gif_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
