"""rework gif storage

Revision ID: df129297ed55
Revises: 4a18bf358b54
Create Date: 2026-07-17 16:29:02.966250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df129297ed55'
down_revision: Union[str, Sequence[str], None] = '4a18bf358b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM user_gif_tags")
    op.execute("DELETE FROM gifs")
    
    op.add_column('gifs', sa.Column("file_hash", sa.String(length=255), nullable=False))
    op.create_unique_constraint("gifs_file_hash_key", 'gifs', ['file_hash'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifs', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('gifs_tg_gif_id_key'), 'gifs', type_='unique')
    op.create_unique_constraint("gifs_file_path_key", 'gifs', ['file_path'])
    op.drop_column('gifs', 'tg_gif_id')
    # ### end Alembic commands ###
    

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('gifs_file_hash_key'), 'gifs', type_='unique')
    op.drop_column('gifs', 'file_hash')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifs', sa.Column('tg_gif_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint("gifs_file_path_key", 'gifs', type_='unique')
    op.create_unique_constraint(op.f('gifs_tg_gif_id_key'), 'gifs', ['tg_gif_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('gifs', 'file_path')
    # ### end Alembic commands ###
